modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "ruokmod"
logoFile = "icon.png"
version = "${version}"
displayName = "RuOK Mod"
authors = "Awei"
description = '''
Rubidium & Sodium Mod!
'''
#logoFile = ""

[[dependencies.ruokmod]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6.2b,)"
ordering = "AFTER"
side = "CLIENT"