modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/MCTeamPotato/RuOK/issues"
license = "GPLv3"

[[mods]]
modId = "ruokmod"
version = "${version}"
displayName = "RuOK Mod"
authors = '''
MCTeamPotato
Awei
'''
description = '''
Embeddium & Sodium Mod!
'''

logoFile = "icon.png"

[[dependencies.ruokmod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "embeddium"
mandatory = true
versionRange = "[0.2.12+mc1.16.5,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.ruokmod]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.17.101,)"
ordering = "AFTER"
side = "CLIENT"