modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MCTeamPotato/RuOK/issues"
license = "GPLv3"

[[mods]]
modId = "ruokmod"
logoFile = "icon.png"
version = "${version}"
displayName = "RuOK Mod"
authors = '''
MCTeamPotato
Awei
'''
description = '''
Rubidium & Sodium Mod!
'''
#logoFile = ""

[[dependencies.ruokmod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "architectury"
mandatory = true
<<<<<<< Updated upstream
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6.2b,)"
=======
versionRange = "[0.3.18+mc1.18.2,)"
>>>>>>> Stashed changes
ordering = "AFTER"
side = "CLIENT"

[[dependencies.ruokmod]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.5.116,)"
ordering = "AFTER"
side = "CLIENT"