modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/MCTeamPotato/RuOK/issues"
license = "GPLv3"

[[mods]]
modId = "ruokmod"
logoFile = "icon.png"
version = "${version}"
displayName = "RuOK Mod"
authors = '''
MCTeamPotato
Awei
'''
description = '''
Embeddium & Sodium Mod!
'''

[[dependencies.ruokmod]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ruokmod]]
modId = "embeddium"
mandatory = true
versionRange = "0.3.0+mc1.19.2"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.ruokmod]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.3.103,)"
ordering = "AFTER"
side = "CLIENT"